# Generated by Django 5.2 on 2025-04-13 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='descriptions',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='course',
            field=models.ManyToManyField(related_name='teachers', to='configapp.course'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='departments',
            field=models.ManyToManyField(related_name='teachers', to='configapp.departments'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='teacher_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
