# Generated by Django 5.2 on 2025-04-13 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0002_rename_descriptions_teacher_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='description',
            new_name='descriptions',
        ),
    ]
