# Generated by Django 5.2 on 2025-04-28 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0002_auto_20250428_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupstudent',
            name='teacher',
        ),
        migrations.AddField(
            model_name='groupstudent',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configapp.teacher'),
            preserve_default=False,
        ),
    ]
