# Generated by Django 5.2 on 2025-04-30 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0003_remove_groupstudent_teacher_groupstudent_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='created_ed',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='date',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='group',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='id',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='updated_ed',
        ),
        migrations.RemoveField(
            model_name='student',
            name='group',
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('group', models.ManyToManyField(to='configapp.groupstudent')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configapp.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='lesson_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='configapp.lesson'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='configapp.groupstudent'),
            preserve_default=False,
        ),
    ]
